# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_dati_registri.models.esito_movimenti_base_model import EsitoMovimentiBaseModel  # noqa: E501

class TestEsitoMovimentiBaseModel(unittest.TestCase):
    """EsitoMovimentiBaseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EsitoMovimentiBaseModel:
        """Test EsitoMovimentiBaseModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EsitoMovimentiBaseModel`
        """
        model = EsitoMovimentiBaseModel()  # noqa: E501
        if include_optional:
            return EsitoMovimentiBaseModel(
                transazione_id = '',
                validazione = [
                    rentri_dati_registri.models.esito_messaggio_model.EsitoMessaggioModel(
                        indice = 56, 
                        campo = '', 
                        tipo = null, 
                        codice_messaggio = '', 
                        parametri = [
                            null
                            ], )
                    ],
                errore = True,
                tempo_elaborazione = ''
            )
        else:
            return EsitoMovimentiBaseModel(
        )
        """

    def testEsitoMovimentiBaseModel(self):
        """Test EsitoMovimentiBaseModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
