# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_dati_registri.models.transazione_request_data_model import TransazioneRequestDataModel  # noqa: E501

class TestTransazioneRequestDataModel(unittest.TestCase):
    """TransazioneRequestDataModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransazioneRequestDataModel:
        """Test TransazioneRequestDataModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransazioneRequestDataModel`
        """
        model = TransazioneRequestDataModel()  # noqa: E501
        if include_optional:
            return TransazioneRequestDataModel(
                claims = '',
                headers = '',
                body = ''
            )
        else:
            return TransazioneRequestDataModel(
        )
        """

    def testTransazioneRequestDataModel(self):
        """Test TransazioneRequestDataModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
