# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_dati_registri.models.info_transazione_model import InfoTransazioneModel  # noqa: E501

class TestInfoTransazioneModel(unittest.TestCase):
    """InfoTransazioneModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InfoTransazioneModel:
        """Test InfoTransazioneModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InfoTransazioneModel`
        """
        model = InfoTransazioneModel()  # noqa: E501
        if include_optional:
            return InfoTransazioneModel(
                identificativo = '',
                tipo = 'Movimenti',
                identificativo_precedente = '',
                data_trasmissione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                identificativo_entita = '',
                data_inizio_elaborazione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                data_fine_elaborazione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status_code_push = 56,
                data_push = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                data_ultimo_pull = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                stato = 'Annullata',
                sorgente = 'Api',
                endpoint = '',
                identificativo_firmatario = '',
                num_iscr_operatore = '',
                identificativo_operatore = '',
                denominazione_operatore = '',
                num_iscr_sito = '',
                sito_comune_id = '',
                sito_provincia_id = '',
                sito_indirizzo = '',
                sito_civico = ''
            )
        else:
            return InfoTransazioneModel(
        )
        """

    def testInfoTransazioneModel(self):
        """Test InfoTransazioneModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
