# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_dati_registri.models.identificativo_movimento_completo_model import IdentificativoMovimentoCompletoModel

class TestIdentificativoMovimentoCompletoModel(unittest.TestCase):
    """IdentificativoMovimentoCompletoModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdentificativoMovimentoCompletoModel:
        """Test IdentificativoMovimentoCompletoModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdentificativoMovimentoCompletoModel`
        """
        model = IdentificativoMovimentoCompletoModel()
        if include_optional:
            return IdentificativoMovimentoCompletoModel(
                anno = 56,
                progressivo = 56,
                identificativo = ''
            )
        else:
            return IdentificativoMovimentoCompletoModel(
        )
        """

    def testIdentificativoMovimentoCompletoModel(self):
        """Test IdentificativoMovimentoCompletoModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
