# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_dati_registri.models.annullamento_movimento_model import AnnullamentoMovimentoModel  # noqa: E501

class TestAnnullamentoMovimentoModel(unittest.TestCase):
    """AnnullamentoMovimentoModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnnullamentoMovimentoModel:
        """Test AnnullamentoMovimentoModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnnullamentoMovimentoModel`
        """
        model = AnnullamentoMovimentoModel()  # noqa: E501
        if include_optional:
            return AnnullamentoMovimentoModel(
                numero_registrazione = rentri_dati_registri.models.anno_progressivo_movimento_model.AnnoProgressivoMovimentoModel(
                    anno = 1980, 
                    progressivo = 1, ),
                data_ora_registrazione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                numero_registrazione_annullata = None,
                annotazioni = '0'
            )
        else:
            return AnnullamentoMovimentoModel(
                numero_registrazione = rentri_dati_registri.models.anno_progressivo_movimento_model.AnnoProgressivoMovimentoModel(
                    anno = 1980, 
                    progressivo = 1, ),
                data_ora_registrazione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                numero_registrazione_annullata = None,
                annotazioni = '0',
        )
        """

    def testAnnullamentoMovimentoModel(self):
        """Test AnnullamentoMovimentoModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
