# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_dati_registri.models.dati_produttore_model import DatiProduttoreModel  # noqa: E501

class TestDatiProduttoreModel(unittest.TestCase):
    """DatiProduttoreModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatiProduttoreModel:
        """Test DatiProduttoreModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatiProduttoreModel`
        """
        model = DatiProduttoreModel()  # noqa: E501
        if include_optional:
            return DatiProduttoreModel(
                denominazione = '',
                codice_fiscale = '01234',
                nazione_id = '',
                indirizzo = rentri_dati_registri.models.indirizzo_model.IndirizzoModel(
                    citta = null, 
                    indirizzo = '0', 
                    civico = '', 
                    cap = '', )
            )
        else:
            return DatiProduttoreModel(
                indirizzo = rentri_dati_registri.models.indirizzo_model.IndirizzoModel(
                    citta = null, 
                    indirizzo = '0', 
                    civico = '', 
                    cap = '', ),
        )
        """

    def testDatiProduttoreModel(self):
        """Test DatiProduttoreModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
