# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_dati_registri.models.dati_respingimento_model import DatiRespingimentoModel

class TestDatiRespingimentoModel(unittest.TestCase):
    """DatiRespingimentoModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatiRespingimentoModel:
        """Test DatiRespingimentoModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatiRespingimentoModel`
        """
        model = DatiRespingimentoModel()
        if include_optional:
            return DatiRespingimentoModel(
                tipo = 'T',
                quantita = rentri_dati_registri.models.unita_misura_quantita_model.UnitaMisuraQuantitaModel(
                    valore = 1.337, 
                    unita_misura = null, ),
                causale = 'NC',
                causale_altro = ''
            )
        else:
            return DatiRespingimentoModel(
                tipo = 'T',
        )
        """

    def testDatiRespingimentoModel(self):
        """Test DatiRespingimentoModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
