# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_dati_registri.models.tipi_respingimento import TipiRespingimento  # noqa: E501

class TestTipiRespingimento(unittest.TestCase):
    """TipiRespingimento unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTipiRespingimento(self):
        """Test TipiRespingimento"""
        # inst = TipiRespingimento()

if __name__ == '__main__':
    unittest.main()
