# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_dati_registri.models.movimento_associato_model import MovimentoAssociatoModel

class TestMovimentoAssociatoModel(unittest.TestCase):
    """MovimentoAssociatoModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MovimentoAssociatoModel:
        """Test MovimentoAssociatoModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MovimentoAssociatoModel`
        """
        model = MovimentoAssociatoModel()
        if include_optional:
            return MovimentoAssociatoModel(
                anno = 56,
                progressivo = 56,
                identificativo = '',
                associazione_diretta = True,
                incompleto = True
            )
        else:
            return MovimentoAssociatoModel(
        )
        """

    def testMovimentoAssociatoModel(self):
        """Test MovimentoAssociatoModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
