# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_dati_registri.models.movimento_info_model import MovimentoInfoModel  # noqa: E501

class TestMovimentoInfoModel(unittest.TestCase):
    """MovimentoInfoModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MovimentoInfoModel:
        """Test MovimentoInfoModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MovimentoInfoModel`
        """
        model = MovimentoInfoModel()  # noqa: E501
        if include_optional:
            return MovimentoInfoModel(
                anno = 56,
                progressivo = 56,
                identificativo = '',
                data_ora_registrazione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return MovimentoInfoModel(
        )
        """

    def testMovimentoInfoModel(self):
        """Test MovimentoInfoModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
