# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_dati_registri.models.dati_riferimenti_completo_model import DatiRiferimentiCompletoModel  # noqa: E501

class TestDatiRiferimentiCompletoModel(unittest.TestCase):
    """DatiRiferimentiCompletoModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatiRiferimentiCompletoModel:
        """Test DatiRiferimentiCompletoModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatiRiferimentiCompletoModel`
        """
        model = DatiRiferimentiCompletoModel()  # noqa: E501
        if include_optional:
            return DatiRiferimentiCompletoModel(
                numero_registrazione = rentri_dati_registri.models.identificativo_movimento_completo_model.IdentificativoMovimentoCompletoModel(
                    anno = 56, 
                    progressivo = 56, 
                    identificativo = '', ),
                data_ora_registrazione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                numero_registrazione_di_rettifica = rentri_dati_registri.models.identificativo_movimento_completo_model.IdentificativoMovimentoCompletoModel(
                    anno = 56, 
                    progressivo = 56, 
                    identificativo = '', ),
                numero_registrazione_rettifica = rentri_dati_registri.models.identificativo_movimento_completo_model.IdentificativoMovimentoCompletoModel(
                    anno = 56, 
                    progressivo = 56, 
                    identificativo = '', ),
                causale_operazione_cs = 'Carico',
                causale_operazione = 'DT',
                stoccaggio_istantaneo = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                riferimenti_operazione = [
                    rentri_dati_registri.models.movimento_associato_model.MovimentoAssociatoModel(
                        anno = 56, 
                        progressivo = 56, 
                        identificativo = '', 
                        associazione_diretta = True, 
                        incompleto = True, )
                    ],
                riferimento_operazione = [
                    rentri_dati_registri.models.movimento_associato_model.MovimentoAssociatoModel(
                        anno = 56, 
                        progressivo = 56, 
                        identificativo = '', 
                        associazione_diretta = True, 
                        incompleto = True, )
                    ],
                identificativo_registro = '',
                num_iscr_sito = '',
                data_creazione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                data_trasmissione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                data_inizio_validita = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                data_fine_validita = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return DatiRiferimentiCompletoModel(
                data_ora_registrazione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testDatiRiferimentiCompletoModel(self):
        """Test DatiRiferimentiCompletoModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
