# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_dati_registri.models.esito_movimenti_model import EsitoMovimentiModel

class TestEsitoMovimentiModel(unittest.TestCase):
    """EsitoMovimentiModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EsitoMovimentiModel:
        """Test EsitoMovimentiModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EsitoMovimentiModel`
        """
        model = EsitoMovimentiModel()
        if include_optional:
            return EsitoMovimentiModel(
                esito = rentri_dati_registri.models.esito_movimenti_data_model.EsitoMovimentiDataModel(
                    identificativo_registro = '', 
                    numero_registrazioni = [
                        rentri_dati_registri.models.identificativo_movimento_completo_model.IdentificativoMovimentoCompletoModel(
                            anno = 56, 
                            progressivo = 56, 
                            identificativo = '', )
                        ], ),
                transazione_id = '',
                validazione = [
                    rentri_dati_registri.models.esito_messaggio_model.EsitoMessaggioModel(
                        indice = 56, 
                        campo = '', 
                        tipo = null, 
                        codice_messaggio = '', 
                        parametri = [
                            null
                            ], )
                    ],
                errore = True,
                tempo_elaborazione = ''
            )
        else:
            return EsitoMovimentiModel(
        )
        """

    def testEsitoMovimentiModel(self):
        """Test EsitoMovimentiModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
