# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_dati_registri.models.dati_intermediario_model import DatiIntermediarioModel

class TestDatiIntermediarioModel(unittest.TestCase):
    """DatiIntermediarioModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatiIntermediarioModel:
        """Test DatiIntermediarioModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatiIntermediarioModel`
        """
        model = DatiIntermediarioModel()
        if include_optional:
            return DatiIntermediarioModel(
                denominazione = '0',
                codice_fiscale = '01234',
                nazione_id = '',
                num_iscrizione_albo = 'AE/807288'
            )
        else:
            return DatiIntermediarioModel(
                denominazione = '0',
                codice_fiscale = '01234',
        )
        """

    def testDatiIntermediarioModel(self):
        """Test DatiIntermediarioModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
