# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_dati_registri.api.soggetto_delegato_api import SoggettoDelegatoApi  # noqa: E501


class TestSoggettoDelegatoApi(unittest.TestCase):
    """SoggettoDelegatoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SoggettoDelegatoApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_soggetto_delegato_identificativo_registro_movimenti_count_get(self) -> None:
        """Test case for soggetto_delegato_identificativo_registro_movimenti_count_get

        Conteggio registrazioni  # noqa: E501
        """
        pass

    def test_soggetto_delegato_identificativo_registro_movimenti_get(self) -> None:
        """Test case for soggetto_delegato_identificativo_registro_movimenti_get

        Elenco registrazioni  # noqa: E501
        """
        pass

    def test_soggetto_delegato_identificativo_registro_movimenti_post(self) -> None:
        """Test case for soggetto_delegato_identificativo_registro_movimenti_post

        🔁[ASYNC] Trasmissione delle registrazioni  # noqa: E501
        """
        pass

    def test_soggetto_delegato_identificativo_registro_movimento_anno_progressivo_get(self) -> None:
        """Test case for soggetto_delegato_identificativo_registro_movimento_anno_progressivo_get

        Dettaglio registrazione per anno e numero  # noqa: E501
        """
        pass

    def test_soggetto_delegato_identificativo_registro_movimento_identificativo_movimento_get(self) -> None:
        """Test case for soggetto_delegato_identificativo_registro_movimento_identificativo_movimento_get

        Dettaglio registrazione per identificativo  # noqa: E501
        """
        pass

    def test_soggetto_delegato_identificativo_registro_valida_post(self) -> None:
        """Test case for soggetto_delegato_identificativo_registro_valida_post

        🔁[ASYNC] Verifica il registro informatico locale  # noqa: E501
        """
        pass

    def test_soggetto_delegato_num_iscr_ass_transazioni_movimenti_num_iscr_sito_get(self) -> None:
        """Test case for soggetto_delegato_num_iscr_ass_transazioni_movimenti_num_iscr_sito_get

        Elenco transazioni  # noqa: E501
        """
        pass

    def test_soggetto_delegato_num_iscr_ass_transazioni_movimenti_num_iscr_sito_identificativo_transazione_get(self) -> None:
        """Test case for soggetto_delegato_num_iscr_ass_transazioni_movimenti_num_iscr_sito_identificativo_transazione_get

        Dettaglio transazione  # noqa: E501
        """
        pass

    def test_soggetto_delegato_num_iscr_ass_transazioni_movimenti_num_iscr_sito_identificativo_transazione_request_get(self) -> None:
        """Test case for soggetto_delegato_num_iscr_ass_transazioni_movimenti_num_iscr_sito_identificativo_transazione_request_get

        Request transazione  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
