# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_dati_registri.models.causali_operazione import CausaliOperazione  # noqa: E501

class TestCausaliOperazione(unittest.TestCase):
    """CausaliOperazione unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCausaliOperazione(self):
        """Test CausaliOperazione"""
        # inst = CausaliOperazione()

if __name__ == '__main__':
    unittest.main()
