# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_dati_registri.models.movimento_dettaglio_model import MovimentoDettaglioModel  # noqa: E501

class TestMovimentoDettaglioModel(unittest.TestCase):
    """MovimentoDettaglioModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MovimentoDettaglioModel:
        """Test MovimentoDettaglioModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MovimentoDettaglioModel`
        """
        model = MovimentoDettaglioModel()  # noqa: E501
        if include_optional:
            return MovimentoDettaglioModel(
                riferimenti = rentri_dati_registri.models.dati_riferimenti_completo_model.DatiRiferimentiCompletoModel(
                    numero_registrazione = null, 
                    data_ora_registrazione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    numero_registrazione_di_rettifica = null, 
                    numero_registrazione_rettifica = null, 
                    causale_operazione_cs = null, 
                    causale_operazione = null, 
                    stoccaggio_istantaneo = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    riferimenti_operazione = [
                        rentri_dati_registri.models.movimento_associato_model.MovimentoAssociatoModel(
                            anno = 56, 
                            progressivo = 56, 
                            identificativo = '', 
                            associazione_diretta = True, 
                            incompleto = True, )
                        ], 
                    riferimento_operazione = [
                        rentri_dati_registri.models.movimento_associato_model.MovimentoAssociatoModel(
                            anno = 56, 
                            progressivo = 56, 
                            identificativo = '', 
                            associazione_diretta = True, 
                            incompleto = True, )
                        ], 
                    identificativo_registro = '', 
                    num_iscr_sito = '', 
                    data_creazione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    data_trasmissione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    data_inizio_validita = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    data_fine_validita = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                rifiuto = rentri_dati_registri.models.dati_rifiuto_model.DatiRifiutoModel(
                    codice_eer = '0', 
                    descrizione_eer = '', 
                    provenienza = null, 
                    caratteristiche_pericolo = [
                        'HP01'
                        ], 
                    stato_fisico = null, 
                    quantita = null, 
                    destinato_attivita = null, 
                    categorie_aee = [
                        'Cat1'
                        ], 
                    veicolo_fuori_uso = True, 
                    veicolo_fuori_uso_reg_pubblica_sicurezza = null, ),
                materiali = rentri_dati_registri.models.dati_materiali_model.DatiMaterialiModel(
                    materiale = null, 
                    descrizione_materiale = '', 
                    quantita = null, ),
                integrazione_fir = rentri_dati_registri.models.dati_integrazione_fir_model.DatiIntegrazioneFirModel(
                    numero_fir = '', 
                    trasporto_transfrontaliero = True, 
                    tipo_trasporto_transfrontaliero = null, 
                    data_inizio_trasporto = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                esito = rentri_dati_registri.models.dati_esito_model.DatiEsitoModel(
                    data_fine_trasporto = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    peso_verificato_destino = 1.337, 
                    respingimento = null, ),
                produttore = rentri_dati_registri.models.dati_produttore_model.DatiProduttoreModel(
                    denominazione = '', 
                    codice_fiscale = '01234', 
                    nazione_id = '', 
                    indirizzo = null, ),
                trasportatore = rentri_dati_registri.models.dati_trasportatore_model.DatiTrasportatoreModel(
                    denominazione = '0', 
                    codice_fiscale = '01234', 
                    nazione_id = '', 
                    num_iscrizione_albo = 'AE/807288', ),
                destinatario = rentri_dati_registri.models.dati_destinatario_model.DatiDestinatarioModel(
                    denominazione = '0', 
                    codice_fiscale = '01234', 
                    nazione_id = '', 
                    num_autorizzazione = '', ),
                intermediario = rentri_dati_registri.models.dati_intermediario_model.DatiIntermediarioModel(
                    denominazione = '0', 
                    codice_fiscale = '01234', 
                    nazione_id = '', 
                    num_iscrizione_albo = 'AE/807288', ),
                intermediari = [
                    rentri_dati_registri.models.dati_intermediario_model.DatiIntermediarioModel(
                        denominazione = '0', 
                        codice_fiscale = '01234', 
                        nazione_id = '', 
                        num_iscrizione_albo = 'AE/807288', )
                    ],
                annotazioni = '',
                annullato = True,
                rettificato = True,
                variazioni = [
                    rentri_dati_registri.models.dati_movimento_model.DatiMovimentoModel(
                        riferimenti = null, 
                        rifiuto = null, 
                        materiali = null, 
                        integrazione_fir = null, 
                        esito = null, 
                        produttore = null, 
                        trasportatore = null, 
                        destinatario = null, 
                        intermediario = null, 
                        intermediari = [
                            rentri_dati_registri.models.dati_intermediario_model.DatiIntermediarioModel(
                                denominazione = '0', 
                                codice_fiscale = '01234', 
                                nazione_id = '', 
                                num_iscrizione_albo = 'AE/807288', )
                            ], 
                        annotazioni = '', 
                        annullato = True, 
                        rettificato = True, )
                    ]
            )
        else:
            return MovimentoDettaglioModel(
        )
        """

    def testMovimentoDettaglioModel(self):
        """Test MovimentoDettaglioModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
