# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_dati_registri.models.sorgente_transazione import SorgenteTransazione  # noqa: E501

class TestSorgenteTransazione(unittest.TestCase):
    """SorgenteTransazione unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSorgenteTransazione(self):
        """Test SorgenteTransazione"""
        # inst = SorgenteTransazione()

if __name__ == '__main__':
    unittest.main()
