# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_dati_registri.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_identificativo_registro_last_transazione_id_get(self) -> None:
        """Test case for identificativo_registro_last_transazione_id_get

        Riferimento ultima transazione
        """
        pass

    def test_status_get(self) -> None:
        """Test case for status_get

        Stato API
        """
        pass

    def test_transazione_id_result_get(self) -> None:
        """Test case for transazione_id_result_get

        Esito transazione
        """
        pass

    def test_transazione_id_status_get(self) -> None:
        """Test case for transazione_id_status_get

        Stato transazione
        """
        pass


if __name__ == '__main__':
    unittest.main()
