# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_dati_registri.models.esito_messaggio_tipo import EsitoMessaggioTipo

class TestEsitoMessaggioTipo(unittest.TestCase):
    """EsitoMessaggioTipo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEsitoMessaggioTipo(self):
        """Test EsitoMessaggioTipo"""
        # inst = EsitoMessaggioTipo()

if __name__ == '__main__':
    unittest.main()
