# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_dati_registri.models.dati_esito_model import DatiEsitoModel  # noqa: E501

class TestDatiEsitoModel(unittest.TestCase):
    """DatiEsitoModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatiEsitoModel:
        """Test DatiEsitoModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatiEsitoModel`
        """
        model = DatiEsitoModel()  # noqa: E501
        if include_optional:
            return DatiEsitoModel(
                data_fine_trasporto = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                peso_verificato_destino = 1.337,
                respingimento = rentri_dati_registri.models.dati_respingimento_model.DatiRespingimentoModel(
                    tipo = null, 
                    quantita = null, 
                    causale = null, 
                    causale_altro = '', )
            )
        else:
            return DatiEsitoModel(
        )
        """

    def testDatiEsitoModel(self):
        """Test DatiEsitoModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
