# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_dati_registri.models.transazione_request_model import TransazioneRequestModel  # noqa: E501

class TestTransazioneRequestModel(unittest.TestCase):
    """TransazioneRequestModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransazioneRequestModel:
        """Test TransazioneRequestModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransazioneRequestModel`
        """
        model = TransazioneRequestModel()  # noqa: E501
        if include_optional:
            return TransazioneRequestModel(
                identificativo_transazione = '',
                jti = '',
                issuer = '',
                date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                endpoint = '',
                data = rentri_dati_registri.models.transazione_request_data_model.TransazioneRequestDataModel(
                    claims = '', 
                    headers = '', 
                    body = '', )
            )
        else:
            return TransazioneRequestModel(
        )
        """

    def testTransazioneRequestModel(self):
        """Test TransazioneRequestModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
