# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_dati_registri.models.dati_riferimenti_base_model_riferimento_operazione_inner import DatiRiferimentiBaseModelRiferimentoOperazioneInner

class TestDatiRiferimentiBaseModelRiferimentoOperazioneInner(unittest.TestCase):
    """DatiRiferimentiBaseModelRiferimentoOperazioneInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatiRiferimentiBaseModelRiferimentoOperazioneInner:
        """Test DatiRiferimentiBaseModelRiferimentoOperazioneInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatiRiferimentiBaseModelRiferimentoOperazioneInner`
        """
        model = DatiRiferimentiBaseModelRiferimentoOperazioneInner()
        if include_optional:
            return DatiRiferimentiBaseModelRiferimentoOperazioneInner(
                anno = 1980,
                progressivo = 1,
                identificativo = 'MW8Q6ZGCKEC0L3O4GI7X0'
            )
        else:
            return DatiRiferimentiBaseModelRiferimentoOperazioneInner(
                anno = 1980,
                progressivo = 1,
                identificativo = 'MW8Q6ZGCKEC0L3O4GI7X0',
        )
        """

    def testDatiRiferimentiBaseModelRiferimentoOperazioneInner(self):
        """Test DatiRiferimentiBaseModelRiferimentoOperazioneInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
