# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_dati_registri.models.dati_rifiuto_model import DatiRifiutoModel

class TestDatiRifiutoModel(unittest.TestCase):
    """DatiRifiutoModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatiRifiutoModel:
        """Test DatiRifiutoModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatiRifiutoModel`
        """
        model = DatiRifiutoModel()
        if include_optional:
            return DatiRifiutoModel(
                codice_eer = '0',
                descrizione_eer = '',
                provenienza = 'U',
                caratteristiche_pericolo = [
                    'HP01'
                    ],
                stato_fisico = 'SP',
                quantita = rentri_dati_registri.models.unita_misura_quantita_model.UnitaMisuraQuantitaModel(
                    valore = 1.337, 
                    unita_misura = null, ),
                destinato_attivita = 'R1',
                categorie_aee = [
                    'Cat1'
                    ],
                veicolo_fuori_uso = True,
                veicolo_fuori_uso_reg_pubblica_sicurezza = rentri_dati_registri.models.veicolo_fuori_uso_reg_pubblica_sicurezza_model.VeicoloFuoriUsoRegPubblicaSicurezzaModel(
                    numero = '0', 
                    data = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return DatiRifiutoModel(
                codice_eer = '0',
                stato_fisico = 'SP',
                quantita = rentri_dati_registri.models.unita_misura_quantita_model.UnitaMisuraQuantitaModel(
                    valore = 1.337, 
                    unita_misura = null, ),
        )
        """

    def testDatiRifiutoModel(self):
        """Test DatiRifiutoModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
