# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_dati_registri.models.veicolo_fuori_uso_reg_pubblica_sicurezza_model import VeicoloFuoriUsoRegPubblicaSicurezzaModel  # noqa: E501

class TestVeicoloFuoriUsoRegPubblicaSicurezzaModel(unittest.TestCase):
    """VeicoloFuoriUsoRegPubblicaSicurezzaModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VeicoloFuoriUsoRegPubblicaSicurezzaModel:
        """Test VeicoloFuoriUsoRegPubblicaSicurezzaModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VeicoloFuoriUsoRegPubblicaSicurezzaModel`
        """
        model = VeicoloFuoriUsoRegPubblicaSicurezzaModel()  # noqa: E501
        if include_optional:
            return VeicoloFuoriUsoRegPubblicaSicurezzaModel(
                numero = '0',
                data = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return VeicoloFuoriUsoRegPubblicaSicurezzaModel(
                numero = '0',
        )
        """

    def testVeicoloFuoriUsoRegPubblicaSicurezzaModel(self):
        """Test VeicoloFuoriUsoRegPubblicaSicurezzaModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
