# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_dati_registri.models.dati_riferimenti_model import DatiRiferimentiModel  # noqa: E501

class TestDatiRiferimentiModel(unittest.TestCase):
    """DatiRiferimentiModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatiRiferimentiModel:
        """Test DatiRiferimentiModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatiRiferimentiModel`
        """
        model = DatiRiferimentiModel()  # noqa: E501
        if include_optional:
            return DatiRiferimentiModel(
                numero_registrazione = rentri_dati_registri.models.anno_progressivo_movimento_model.AnnoProgressivoMovimentoModel(
                    anno = 1980, 
                    progressivo = 1, ),
                data_ora_registrazione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                causale_operazione = 'DT',
                stoccaggio_istantaneo = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                numero_registrazione_rettifica = None,
                riferimento_operazione = [
                    null
                    ]
            )
        else:
            return DatiRiferimentiModel(
                numero_registrazione = rentri_dati_registri.models.anno_progressivo_movimento_model.AnnoProgressivoMovimentoModel(
                    anno = 1980, 
                    progressivo = 1, ),
                data_ora_registrazione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testDatiRiferimentiModel(self):
        """Test DatiRiferimentiModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
