# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_dati_registri.models.causali_operazione_cs import CausaliOperazioneCs

class TestCausaliOperazioneCs(unittest.TestCase):
    """CausaliOperazioneCs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCausaliOperazioneCs(self):
        """Test CausaliOperazioneCs"""
        # inst = CausaliOperazioneCs()

if __name__ == '__main__':
    unittest.main()
