# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_dati_registri.models.unita_misura_peso import UnitaMisuraPeso

class TestUnitaMisuraPeso(unittest.TestCase):
    """UnitaMisuraPeso unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnitaMisuraPeso(self):
        """Test UnitaMisuraPeso"""
        # inst = UnitaMisuraPeso()

if __name__ == '__main__':
    unittest.main()
