# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CategorieAee(str, Enum):
    """
    CategorieAee
    """

    """
    allowed enum values
    """
    CAT1 = 'Cat1'
    CAT2 = 'Cat2'
    CAT3 = 'Cat3'
    CAT4 = 'Cat4'
    CAT5 = 'Cat5'
    CAT6 = 'Cat6'
    PF = 'PF'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CategorieAee from a JSON string"""
        return cls(json.loads(json_str))


