# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class CausaliOperazioneCs(str, Enum):
    """
    CausaliOperazioneCs
    """

    """
    allowed enum values
    """
    CARICO = 'Carico'
    SCARICO = 'Scarico'
    CARICOSCARICO = 'CaricoScarico'

    @classmethod
    def from_json(cls, json_str: str) -> CausaliOperazioneCs:
        """Create an instance of CausaliOperazioneCs from a JSON string"""
        return CausaliOperazioneCs(json.loads(json_str))


