# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class CausaliRespingimento(str, Enum):
    """
    CausaliRespingimento
    """

    """
    allowed enum values
    """
    NC = 'NC'
    IR = 'IR'
    A = 'A'

    @classmethod
    def from_json(cls, json_str: str) -> CausaliRespingimento:
        """Create an instance of CausaliRespingimento from a JSON string"""
        return CausaliRespingimento(json.loads(json_str))


