# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CausaliOperazione(str, Enum):
    """
    CausaliOperazione
    """

    """
    allowed enum values
    """
    DT = 'DT'
    NP = 'NP'
    T_STAR = 'T*'
    RE = 'RE'
    I = 'I'
    AT = 'aT'
    M = 'M'
    TR = 'TR'
    T_STAR_A_T = 'T*aT'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CausaliOperazione from a JSON string"""
        return cls(json.loads(json_str))


