# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class DatiDestinatarioModel(BaseModel):
    """
    Destinatario
    """ # noqa: E501
    denominazione: Annotated[str, Field(min_length=1, strict=True, max_length=255)] = Field(description="Denominazione del soggetto")
    codice_fiscale: Annotated[str, Field(min_length=5, strict=True, max_length=20)] = Field(description="Codice fiscale")
    nazione_id: Optional[Annotated[str, Field(strict=True, max_length=2)]] = Field(default=None, description="Codice ISO 3166-1 alpha-2 della nazione, in caso di \"IT\" è possibile omettere.  Vengono accettati solo codici previsti dallo standard ISO 3166-1 alpha-2.  Vedi API di codifica: <i>GET /codifiche/v1.0/nazioni</i>  <i>Questo campo viene utilizzato esclusivamente per validare i dati di input in base alla nazione di appartenenza (non viene memorizzato e quindi restituito in output).</i>")
    num_autorizzazione: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, description="Numero autorizzazione. Non obbligatorio nel caso di destinatario estero, richiesto in caso contrario")
    __properties: ClassVar[List[str]] = ["denominazione", "codice_fiscale", "nazione_id", "num_autorizzazione"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DatiDestinatarioModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if nazione_id (nullable) is None
        # and model_fields_set contains the field
        if self.nazione_id is None and "nazione_id" in self.model_fields_set:
            _dict['nazione_id'] = None

        # set to None if num_autorizzazione (nullable) is None
        # and model_fields_set contains the field
        if self.num_autorizzazione is None and "num_autorizzazione" in self.model_fields_set:
            _dict['num_autorizzazione'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DatiDestinatarioModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "denominazione": obj.get("denominazione"),
            "codice_fiscale": obj.get("codice_fiscale"),
            "nazione_id": obj.get("nazione_id"),
            "num_autorizzazione": obj.get("num_autorizzazione")
        })
        return _obj


