# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from rentri_dati_registri.models.indirizzo_model import IndirizzoModel
from typing import Optional, Set
from typing_extensions import Self

class DatiProduttoreModel(BaseModel):
    """
    Produttore
    """ # noqa: E501
    denominazione: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Denominazione del soggetto")
    codice_fiscale: Optional[Annotated[str, Field(min_length=5, strict=True, max_length=20)]] = Field(default=None, description="Codice fiscale")
    nazione_id: Optional[Annotated[str, Field(strict=True, max_length=2)]] = Field(default=None, description="Codice ISO 3166-1 alpha-2 della nazione, in caso di \"IT\" è possibile omettere.  Vengono accettati solo codici previsti dallo standard ISO 3166-1 alpha-2.  Vedi API di codifica: <i>GET /codifiche/v1.0/nazioni</i>  <i>Questo campo viene utilizzato esclusivamente per validare i dati di input in base alla nazione di appartenenza (non viene memorizzato e quindi restituito in output).</i>")
    indirizzo: IndirizzoModel = Field(description="Indirizzo")
    __properties: ClassVar[List[str]] = ["denominazione", "codice_fiscale", "nazione_id", "indirizzo"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DatiProduttoreModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of indirizzo
        if self.indirizzo:
            _dict['indirizzo'] = self.indirizzo.to_dict()
        # set to None if denominazione (nullable) is None
        # and model_fields_set contains the field
        if self.denominazione is None and "denominazione" in self.model_fields_set:
            _dict['denominazione'] = None

        # set to None if codice_fiscale (nullable) is None
        # and model_fields_set contains the field
        if self.codice_fiscale is None and "codice_fiscale" in self.model_fields_set:
            _dict['codice_fiscale'] = None

        # set to None if nazione_id (nullable) is None
        # and model_fields_set contains the field
        if self.nazione_id is None and "nazione_id" in self.model_fields_set:
            _dict['nazione_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DatiProduttoreModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "denominazione": obj.get("denominazione"),
            "codice_fiscale": obj.get("codice_fiscale"),
            "nazione_id": obj.get("nazione_id"),
            "indirizzo": IndirizzoModel.from_dict(obj["indirizzo"]) if obj.get("indirizzo") is not None else None
        })
        return _obj


