# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from rentri_dati_registri.models.dati_respingimento_model import DatiRespingimentoModel
from typing import Optional, Set
from typing_extensions import Self

class DatiEsitoModel(BaseModel):
    """
    Esito conferimento
    """ # noqa: E501
    data_fine_trasporto: Optional[datetime] = Field(default=None, description="Data di fine trasporto (formato ISO 8601 UTC)")
    peso_verificato_destino: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Peso verificato a destino (parte intera: 10, parte decimale: 4) compreso tra 0.0000 e 9999999999.9999.")
    respingimento: Optional[DatiRespingimentoModel] = Field(default=None, description="Dati sul respingimento")
    __properties: ClassVar[List[str]] = ["data_fine_trasporto", "peso_verificato_destino", "respingimento"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DatiEsitoModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of respingimento
        if self.respingimento:
            _dict['respingimento'] = self.respingimento.to_dict()
        # set to None if data_fine_trasporto (nullable) is None
        # and model_fields_set contains the field
        if self.data_fine_trasporto is None and "data_fine_trasporto" in self.model_fields_set:
            _dict['data_fine_trasporto'] = None

        # set to None if peso_verificato_destino (nullable) is None
        # and model_fields_set contains the field
        if self.peso_verificato_destino is None and "peso_verificato_destino" in self.model_fields_set:
            _dict['peso_verificato_destino'] = None

        # set to None if respingimento (nullable) is None
        # and model_fields_set contains the field
        if self.respingimento is None and "respingimento" in self.model_fields_set:
            _dict['respingimento'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DatiEsitoModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "data_fine_trasporto": obj.get("data_fine_trasporto"),
            "peso_verificato_destino": obj.get("peso_verificato_destino"),
            "respingimento": DatiRespingimentoModel.from_dict(obj["respingimento"]) if obj.get("respingimento") is not None else None
        })
        return _obj


