# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from rentri_dati_registri.models.identificativo_movimento_completo_model import IdentificativoMovimentoCompletoModel
from typing import Optional, Set
from typing_extensions import Self

class EsitoMovimentiDataModel(BaseModel):
    """
    EsitoMovimentiDataModel
    """ # noqa: E501
    identificativo_registro: Optional[StrictStr] = Field(default=None, description="Identificativo del registro")
    numero_registrazioni: Optional[List[IdentificativoMovimentoCompletoModel]] = Field(default=None, description="Elenco degli identificativi delle registrazioni")
    __properties: ClassVar[List[str]] = ["identificativo_registro", "numero_registrazioni"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EsitoMovimentiDataModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in numero_registrazioni (list)
        _items = []
        if self.numero_registrazioni:
            for _item_numero_registrazioni in self.numero_registrazioni:
                if _item_numero_registrazioni:
                    _items.append(_item_numero_registrazioni.to_dict())
            _dict['numero_registrazioni'] = _items
        # set to None if identificativo_registro (nullable) is None
        # and model_fields_set contains the field
        if self.identificativo_registro is None and "identificativo_registro" in self.model_fields_set:
            _dict['identificativo_registro'] = None

        # set to None if numero_registrazioni (nullable) is None
        # and model_fields_set contains the field
        if self.numero_registrazioni is None and "numero_registrazioni" in self.model_fields_set:
            _dict['numero_registrazioni'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EsitoMovimentiDataModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "identificativo_registro": obj.get("identificativo_registro"),
            "numero_registrazioni": [IdentificativoMovimentoCompletoModel.from_dict(_item) for _item in obj["numero_registrazioni"]] if obj.get("numero_registrazioni") is not None else None
        })
        return _obj


