# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Materiali(str, Enum):
    """
    Materiali
    """

    """
    allowed enum values
    """
    ACV = 'ACV'
    ACM = 'ACM'
    AA = 'AA'
    DIG = 'DIG'
    AGG = 'AGG'
    RA = 'RA'
    RV = 'RV'
    RFA = 'RFA'
    RR = 'RR'
    CC = 'CC'
    PLA = 'PLA'
    LS = 'LS'
    CSS = 'CSS'
    TE = 'TE'
    GOM = 'GOM'
    CU = 'CU'
    MC = 'MC'
    CF = 'CF'
    AF = 'AF'
    GCB = 'GCB'
    ASS = 'ASS'
    GMV = 'GMV'
    A = 'A'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Materiali from a JSON string"""
        return cls(json.loads(json_str))


