# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MovimentoInfoModel(BaseModel):
    """
    MovimentoInfoModel
    """ # noqa: E501
    anno: Optional[StrictInt] = None
    progressivo: Optional[StrictInt] = None
    identificativo: Optional[StrictStr] = None
    data_ora_registrazione: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["anno", "progressivo", "identificativo", "data_ora_registrazione"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MovimentoInfoModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if anno (nullable) is None
        # and model_fields_set contains the field
        if self.anno is None and "anno" in self.model_fields_set:
            _dict['anno'] = None

        # set to None if progressivo (nullable) is None
        # and model_fields_set contains the field
        if self.progressivo is None and "progressivo" in self.model_fields_set:
            _dict['progressivo'] = None

        # set to None if identificativo (nullable) is None
        # and model_fields_set contains the field
        if self.identificativo is None and "identificativo" in self.model_fields_set:
            _dict['identificativo'] = None

        # set to None if data_ora_registrazione (nullable) is None
        # and model_fields_set contains the field
        if self.data_ora_registrazione is None and "data_ora_registrazione" in self.model_fields_set:
            _dict['data_ora_registrazione'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MovimentoInfoModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "anno": obj.get("anno"),
            "progressivo": obj.get("progressivo"),
            "identificativo": obj.get("identificativo"),
            "data_ora_registrazione": obj.get("data_ora_registrazione")
        })
        return _obj


