# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, StrictInt, StrictStr

class MovimentoInfoModel(BaseModel):
    """
    MovimentoInfoModel
    """
    anno: Optional[StrictInt] = None
    progressivo: Optional[StrictInt] = None
    identificativo: Optional[StrictStr] = None
    data_ora_registrazione: Optional[datetime] = None
    __properties = ["anno", "progressivo", "identificativo", "data_ora_registrazione"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MovimentoInfoModel:
        """Create an instance of MovimentoInfoModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if anno (nullable) is None
        # and __fields_set__ contains the field
        if self.anno is None and "anno" in self.__fields_set__:
            _dict['anno'] = None

        # set to None if progressivo (nullable) is None
        # and __fields_set__ contains the field
        if self.progressivo is None and "progressivo" in self.__fields_set__:
            _dict['progressivo'] = None

        # set to None if identificativo (nullable) is None
        # and __fields_set__ contains the field
        if self.identificativo is None and "identificativo" in self.__fields_set__:
            _dict['identificativo'] = None

        # set to None if data_ora_registrazione (nullable) is None
        # and __fields_set__ contains the field
        if self.data_ora_registrazione is None and "data_ora_registrazione" in self.__fields_set__:
            _dict['data_ora_registrazione'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MovimentoInfoModel:
        """Create an instance of MovimentoInfoModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return MovimentoInfoModel.parse_obj(obj)

        _obj = MovimentoInfoModel.parse_obj({
            "anno": obj.get("anno"),
            "progressivo": obj.get("progressivo"),
            "identificativo": obj.get("identificativo"),
            "data_ora_registrazione": obj.get("data_ora_registrazione")
        })
        return _obj


