# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, conlist, constr
from rentri_dati_registri.models.dati_destinatario_model import DatiDestinatarioModel
from rentri_dati_registri.models.dati_esito_model import DatiEsitoModel
from rentri_dati_registri.models.dati_integrazione_fir_model import DatiIntegrazioneFirModel
from rentri_dati_registri.models.dati_intermediario_model import DatiIntermediarioModel
from rentri_dati_registri.models.dati_materiali_model import DatiMaterialiModel
from rentri_dati_registri.models.dati_produttore_model import DatiProduttoreModel
from rentri_dati_registri.models.dati_riferimenti_base_model import DatiRiferimentiBaseModel
from rentri_dati_registri.models.dati_rifiuto_model import DatiRifiutoModel
from rentri_dati_registri.models.dati_trasportatore_model import DatiTrasportatoreModel

class MovimentoBaseModel(BaseModel):
    """
    Dati della registrazione  # noqa: E501
    """
    riferimenti: DatiRiferimentiBaseModel = Field(default=..., description="Riferimenti operazione")
    rifiuto: Optional[DatiRifiutoModel] = Field(default=None, description="Identificazione del rifiuto.  Richiesto solamente se causale_operazione è diversa da \"M\".")
    materiali: Optional[DatiMaterialiModel] = Field(default=None, description="Materiali (solo impianti).  Richiesto solamente se causale_operazione è uguale a \"M\".")
    integrazione_fir: Optional[DatiIntegrazioneFirModel] = Field(default=None, description="Integrazione FIR - Registro C/S.  Non deve essere indicato se causale_operazione è diversa da \"aT\", \"TR\", \"T*\", \"T*AT\".")
    esito: Optional[DatiEsitoModel] = Field(default=None, description="Esito conferimento.  Non deve essere indicato se causale_operazione è diversa da \"aT\", \"T*AT\".")
    produttore: Optional[DatiProduttoreModel] = Field(default=None, description="Produttore del rifiuto")
    trasportatore: Optional[DatiTrasportatoreModel] = Field(default=None, description="Trasportatore")
    destinatario: Optional[DatiDestinatarioModel] = Field(default=None, description="Destinatario")
    intermediario: Optional[DatiIntermediarioModel] = Field(default=None, description="Intermediario     ⚠️ Deprecato: utilizzare \"Intermediari\"")
    intermediari: Optional[conlist(DatiIntermediarioModel)] = Field(default=None, description="Intermediari")
    annotazioni: Optional[constr(strict=True, max_length=500)] = Field(default=None, description="Annotazioni generiche")
    __properties = []

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MovimentoBaseModel:
        """Create an instance of MovimentoBaseModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MovimentoBaseModel:
        """Create an instance of MovimentoBaseModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return MovimentoBaseModel.parse_obj(obj)

        _obj = MovimentoBaseModel.parse_obj({
        })
        return _obj


