# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class StatoTransazione(str, Enum):
    """
    StatoTransazione
    """

    """
    allowed enum values
    """
    ANNULLATA = 'Annullata'
    INERRORE = 'InErrore'
    NUOVA = 'Nuova'
    CONCLUSA = 'Conclusa'
    INLAVORAZIONE = 'InLavorazione'
    CONCLUSACOMUNICATA = 'ConclusaComunicata'
    ERROREDISISTEMA = 'ErroreDiSistema'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of StatoTransazione from a JSON string"""
        return cls(json.loads(json_str))


