# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class StatiEsitoConferimento(str, Enum):
    """
    StatiEsitoConferimento
    """

    """
    allowed enum values
    """
    NONPRESENTE = 'NonPresente'
    ACCOLTO = 'Accolto'
    RESPINTO = 'Respinto'
    QUALUNQUE = 'Qualunque'

    @classmethod
    def from_json(cls, json_str: str) -> StatiEsitoConferimento:
        """Create an instance of StatiEsitoConferimento from a JSON string"""
        return StatiEsitoConferimento(json.loads(json_str))


