# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class TipiRespingimento(str, Enum):
    """
    TipiRespingimento
    """

    """
    allowed enum values
    """
    T = 'T'
    P = 'P'

    @classmethod
    def from_json(cls, json_str: str) -> TipiRespingimento:
        """Create an instance of TipiRespingimento from a JSON string"""
        return TipiRespingimento(json.loads(json_str))


