# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class TipiTrasportoTransfrontaliero(str, Enum):
    """
    TipiTrasportoTransfrontaliero
    """

    """
    allowed enum values
    """
    DM = 'DM'
    DA = 'DA'

    @classmethod
    def from_json(cls, json_str: str) -> TipiTrasportoTransfrontaliero:
        """Create an instance of TipiTrasportoTransfrontaliero from a JSON string"""
        return TipiTrasportoTransfrontaliero(json.loads(json_str))


