# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TipiTrasportoTransfrontaliero(str, Enum):
    """
    TipiTrasportoTransfrontaliero
    """

    """
    allowed enum values
    """
    DM = 'DM'
    DA = 'DA'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TipiTrasportoTransfrontaliero from a JSON string"""
        return cls(json.loads(json_str))


