# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr

class TransazioneRequestDataModel(BaseModel):
    """
    TransazioneRequestDataModel
    """
    claims: Optional[StrictStr] = None
    headers: Optional[StrictStr] = None
    body: Optional[StrictStr] = None
    __properties = ["claims", "headers", "body"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TransazioneRequestDataModel:
        """Create an instance of TransazioneRequestDataModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if claims (nullable) is None
        # and __fields_set__ contains the field
        if self.claims is None and "claims" in self.__fields_set__:
            _dict['claims'] = None

        # set to None if headers (nullable) is None
        # and __fields_set__ contains the field
        if self.headers is None and "headers" in self.__fields_set__:
            _dict['headers'] = None

        # set to None if body (nullable) is None
        # and __fields_set__ contains the field
        if self.body is None and "body" in self.__fields_set__:
            _dict['body'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TransazioneRequestDataModel:
        """Create an instance of TransazioneRequestDataModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TransazioneRequestDataModel.parse_obj(obj)

        _obj = TransazioneRequestDataModel.parse_obj({
            "claims": obj.get("claims"),
            "headers": obj.get("headers"),
            "body": obj.get("body")
        })
        return _obj


