# coding: utf-8

"""
    dati-registri

    Servizio dati registri RENTRI

    The version of the OpenAPI document: 1.0.20250114-613
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, constr

class VeicoloFuoriUsoRegPubblicaSicurezzaModel(BaseModel):
    """
    Registro pubblica sicurezza  # noqa: E501
    """
    numero: constr(strict=True, max_length=50, min_length=1) = Field(default=..., description="Numero reg. pubblica sicurezza")
    data: Optional[datetime] = Field(default=None, description="Data reg. pubblica sicurezza (formato ISO 8601 UTC)")
    __properties = ["numero", "data"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> VeicoloFuoriUsoRegPubblicaSicurezzaModel:
        """Create an instance of VeicoloFuoriUsoRegPubblicaSicurezzaModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if data (nullable) is None
        # and __fields_set__ contains the field
        if self.data is None and "data" in self.__fields_set__:
            _dict['data'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> VeicoloFuoriUsoRegPubblicaSicurezzaModel:
        """Create an instance of VeicoloFuoriUsoRegPubblicaSicurezzaModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return VeicoloFuoriUsoRegPubblicaSicurezzaModel.parse_obj(obj)

        _obj = VeicoloFuoriUsoRegPubblicaSicurezzaModel.parse_obj({
            "numero": obj.get("numero"),
            "data": obj.get("data")
        })
        return _obj


